Feature shared bus
DoneTech-IoT/IoTPlatform pull request #13
Opened 2024-08-31 13:14 UTC by m4github

send and receive a queue between components.

2024-08-31 13:20 UTC, m4github commented
restore main file changes.

2024-08-31 13:20 UTC, m4github commented
Add comments on the shared-bus-receive function and remove extra comments.

2024-09-02 01:09 UTC, Behn4m commented on main/app_main.cpp
why you are updating the `main.c`? if you want to test and demo the code, you can use the https://github.com/DoneTech-IoT/InterCom-test-code repo for it.

2024-09-02 01:24 UTC, Behn4m requested changes

2024-09-02 01:24 UTC, Behn4m commented on components/lvgl_esp32_drivers/lvgl_tft/rm67162Lilygo.h
> -#define TFT_SPI_HOST          SPI2_HOST
what is this?

2024-09-02 01:24 UTC, Behn4m commented on main/app_main.cpp
why are you updating the `main.c?` if you want to test and demo the code, you can use the https://github.com/DoneTech-IoT/InterCom-test-code repo for it.

2024-09-02 01:24 UTC, Behn4m commented on main/ServiceManger.cpp
> -    char pcTaskList[TASK_LIST_BUFFER_SIZE];
why this line commented?

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +static EventGroupHandle_t EventGroupHandleLocal;
this is not local variable

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +esp_err_t SharedBusInit(EventGroupHandle_t *EventGroupHandle,QueueHandle_t *QueueHandle)
no unit test? check if input arguments are not `null`

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +{
add the unit test

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +                    1);/* Wait a maximum of 100ms for either bit to be set. */
magic number?

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +    EventBits = xEventGroupSetBits(
what happens in the case of timeout? Do you want to send the next queue anyway?

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +    EventBits = xEventGroupSetBits(
Sending after a timeout should be notified in the log.

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +{
add unit test at the begining of the function.

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +            ESP_LOGE(TAG, "Recieved-%d", SharedBusPacket.SourceID);
1- put code under if in `{...}` even if it is one line of code
2- I think you should `return 0` after this error

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.cpp
> +            ESP_LOGE(TAG, "Peek-%d", SharedBusPacket.SourceID);
same comment as above

2024-09-02 01:24 UTC, Behn4m commented on components/Utilities/SharedBus/SharedBus.h
> +esp_err_t SharedBusInit(EventGroupHandle_t *EventGroupHandle,QueueHandle_t *QueueHandle);
add a Doxygen format comment for funtions

2024-09-08 08:20 UTC, m4github commented
This PR is going to be close. I will send another PR for SharedBus feature and fix every comment you posted on this PR. @Behn4m

2024-09-08 09:18 UTC, m4github commented on components/Utilities/SharedBus/SharedBus.cpp
> +static EventGroupHandle_t EventGroupHandleLocal;
why not! @Behn4m

2024-09-11 13:53 UTC, closed without merging